FROM python:3.11-slim

WORKDIR /opt/gnl

# Dépendances système
RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc \
    && rm -rf /var/lib/apt/lists/*

# Dépendances Python
COPY raspberry_pi/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Code source
COPY raspberry_pi/ .

# Logs
RUN mkdir -p /var/log/gnl

# Port API REST
EXPOSE 5000

CMD ["python3", "gnl_main.py"]
